[2025-09-13T09:41:05.384+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:41:05.553+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_marts.marts.dim_customers.run manual__2025-09-13T09:40:29.757092+00:00 [queued]>
[2025-09-13T09:41:05.574+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_marts.marts.dim_customers.run manual__2025-09-13T09:40:29.757092+00:00 [queued]>
[2025-09-13T09:41:05.576+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:41:05.618+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunVirtualenvOperator): marts.dim_customers.run> on 2025-09-13 09:40:29.757092+00:00
[2025-09-13T09:41:05.629+0000] {standard_task_runner.py:64} INFO - Started process 6309 to run task
[2025-09-13T09:41:05.638+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_marts', 'marts.dim_customers.run', 'manual__2025-09-13T09:40:29.757092+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/dbt_marts.py', '--cfg-path', '/tmp/tmp450gidaw']
[2025-09-13T09:41:05.643+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask marts.dim_customers.run
[2025-09-13T09:41:15.906+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-13T09:41:15.907+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-09-13T09:41:15.911+0000] {process_utils.py:132} INFO - Sending 15 to group 6309. PIDs of all processes in the group: [6309]
[2025-09-13T09:41:15.912+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 6309
[2025-09-13T09:41:16.246+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=6309, status='terminated', exitcode=0, started='09:41:05') (6309) terminated with exit code 0
