[2025-09-13T09:43:05.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:43:05.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.payment_methods.test manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:43:05.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.payment_methods.test manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:43:05.286+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:43:05.310+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestVirtualenvOperator): intermediate.payment_methods.test> on 2025-09-13 09:41:16.265222+00:00
[2025-09-13T09:43:05.320+0000] {standard_task_runner.py:64} INFO - Started process 6788 to run task
[2025-09-13T09:43:05.325+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.payment_methods.test', 'manual__2025-09-13T09:41:16.265222+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmp2l1o6kd3']
[2025-09-13T09:43:05.330+0000] {standard_task_runner.py:91} INFO - Job 224: Subtask intermediate.payment_methods.test
[2025-09-13T09:43:05.564+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.payment_methods.test manual__2025-09-13T09:41:16.265222+00:00 [running]> on host e95bde6b8d07
[2025-09-13T09:43:06.004+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.payment_methods.test' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T09:41:16.265222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T09:41:16.265222+00:00'
[2025-09-13T09:43:06.008+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T09:43:06.037+0000] {baseoperator.py:400} WARNING - DbtTestVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-09-13T09:43:06.038+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock exists
[2025-09-13T09:43:06.039+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:06.041+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:06.041+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:07.043+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:07.044+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:07.044+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:08.045+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:08.048+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:08.049+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:09.052+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:09.052+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:09.053+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:10.055+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:10.056+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:10.056+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:11.057+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:11.058+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:11.059+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:12.061+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:12.062+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:12.062+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:13.064+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:13.064+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:13.065+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:14.066+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:14.067+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:14.068+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:15.069+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:15.070+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:15.071+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:16.073+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:16.073+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:16.074+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:17.075+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:17.076+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:17.077+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:18.079+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:18.080+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:18.081+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:19.082+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6487
[2025-09-13T09:43:19.083+0000] {virtualenv.py:181} INFO - Process 6487 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:43:19.083+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:43:20.085+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-13T09:43:20.086+0000] {virtualenv.py:210} WARNING - Lockfile owned by process of pid 6789, while operator has pid 6788
[2025-09-13T09:43:20.086+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T09:43:20.087+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 1089, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 121, in run_command
    while not self._is_lock_available() and self.max_retries_lock:
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 52, in wrapper
    return method(operator, *args)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 177, in _is_lock_available
    pid = int(lf.read())
ValueError: invalid literal for int() with base 10: ''
[2025-09-13T09:43:20.132+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.payment_methods.test, run_id=manual__2025-09-13T09:41:16.265222+00:00, execution_date=20250913T094116, start_date=20250913T094305, end_date=20250913T094320
[2025-09-13T09:43:20.205+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 224 for task intermediate.payment_methods.test (invalid literal for int() with base 10: ''; 6788)
[2025-09-13T09:43:20.226+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-13T09:43:20.290+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T09:43:20.348+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
