[2025-09-13T09:41:22.055+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T09:41:22.342+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.categories_enriched.run manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:41:22.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_intermediate.intermediate.categories_enriched.run manual__2025-09-13T09:41:16.265222+00:00 [queued]>
[2025-09-13T09:41:22.367+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T09:41:22.409+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunVirtualenvOperator): intermediate.categories_enriched.run> on 2025-09-13 09:41:16.265222+00:00
[2025-09-13T09:41:22.425+0000] {standard_task_runner.py:64} INFO - Started process 6357 to run task
[2025-09-13T09:41:22.430+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_intermediate', 'intermediate.categories_enriched.run', 'manual__2025-09-13T09:41:16.265222+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/dbt_intermediate.py', '--cfg-path', '/tmp/tmpth4wjszc']
[2025-09-13T09:41:22.435+0000] {standard_task_runner.py:91} INFO - Job 218: Subtask intermediate.categories_enriched.run
[2025-09-13T09:41:22.729+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_intermediate.intermediate.categories_enriched.run manual__2025-09-13T09:41:16.265222+00:00 [running]> on host e95bde6b8d07
[2025-09-13T09:41:23.056+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_intermediate' AIRFLOW_CTX_TASK_ID='intermediate.categories_enriched.run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T09:41:16.265222+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-13T09:41:16.265222+00:00'
[2025-09-13T09:41:23.058+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T09:41:23.079+0000] {virtualenv.py:120} INFO - Checking if the virtualenv lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock exists
[2025-09-13T09:41:23.080+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:23.081+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:23.082+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:24.084+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:24.085+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:24.086+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:25.088+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:25.089+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:25.089+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:26.091+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:26.092+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:26.092+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:27.094+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:27.094+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:27.095+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:28.097+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:28.098+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:28.098+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:29.100+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:29.101+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:29.101+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:30.104+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:30.105+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:30.106+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:31.108+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:31.110+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:31.111+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:32.113+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:32.114+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:32.114+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:33.116+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:33.117+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:33.118+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:34.120+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:34.121+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:34.124+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:35.126+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:35.127+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:35.127+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:36.129+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6351
[2025-09-13T09:41:36.130+0000] {virtualenv.py:181} INFO - Process 6351 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:36.131+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:37.132+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:37.133+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:37.133+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:38.134+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:38.134+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:38.135+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:39.135+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:39.136+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:39.137+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:40.138+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:40.142+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:40.158+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:41.160+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:41.161+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:41.162+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:42.164+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:42.165+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:42.165+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:43.168+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:43.170+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:43.171+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:44.173+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:44.174+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:44.174+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:45.176+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:45.177+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:45.178+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:46.179+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:46.180+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:46.181+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:47.182+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:47.183+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:47.183+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:48.185+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:48.194+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:48.210+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:49.212+0000] {virtualenv.py:178} INFO - Checking for running process with PID 6354
[2025-09-13T09:41:49.213+0000] {virtualenv.py:181} INFO - Process 6354 running: True and has the lock /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock.
[2025-09-13T09:41:49.214+0000] {virtualenv.py:122} INFO - Waiting for virtualenv lock to be released
[2025-09-13T09:41:50.215+0000] {virtualenv.py:126} INFO - Acquiring the virtualenv lock
[2025-09-13T09:41:50.216+0000] {virtualenv.py:195} INFO - Acquiring lock at /tmp/cosmos_venv_ecom/cosmos_virtualenv.lock with pid 6357
[2025-09-13T09:41:50.217+0000] {virtualenv.py:153} INFO - Creating or updating the virtualenv at `/tmp/cosmos_venv_ecom
[2025-09-13T09:41:50.217+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/cosmos_venv_ecom --python=python3
[2025-09-13T09:41:50.218+0000] {process_utils.py:187} INFO - Output:
[2025-09-13T09:41:51.552+0000] {process_utils.py:191} INFO - RuntimeError: failed to build image setuptools because:
[2025-09-13T09:41:51.554+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2025-09-13T09:41:51.555+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
[2025-09-13T09:41:51.556+0000] {process_utils.py:191} INFO -     installer.install(creator.interpreter.version_info)
[2025-09-13T09:41:51.556+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 37, in install
[2025-09-13T09:41:51.557+0000] {process_utils.py:191} INFO -     self._sync(filename, into)
[2025-09-13T09:41:51.557+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/pip_install/copy.py", line 13, in _sync
[2025-09-13T09:41:51.557+0000] {process_utils.py:191} INFO -     copy(src, dst)
[2025-09-13T09:41:51.558+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/util/path/_sync.py", line 41, in copy
[2025-09-13T09:41:51.558+0000] {process_utils.py:191} INFO -     method(str(src), str(dest))
[2025-09-13T09:41:51.559+0000] {process_utils.py:191} INFO -   File "/home/***/.local/lib/python3.10/site-packages/virtualenv/util/path/_sync.py", line 52, in copytree
[2025-09-13T09:41:51.559+0000] {process_utils.py:191} INFO -     shutil.copy(src_f, dest_f)
[2025-09-13T09:41:51.559+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.10/shutil.py", line 418, in copy
[2025-09-13T09:41:51.560+0000] {process_utils.py:191} INFO -     copymode(src, dst, follow_symlinks=follow_symlinks)
[2025-09-13T09:41:51.560+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.10/shutil.py", line 307, in copymode
[2025-09-13T09:41:51.560+0000] {process_utils.py:191} INFO -     chmod_func(dst, stat.S_IMODE(st.st_mode))
[2025-09-13T09:41:51.561+0000] {process_utils.py:191} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cosmos_venv_ecom/lib/python3.10/site-packages/setuptools/_vendor/backports/tarfile/__init__.py'
[2025-09-13T09:41:51.561+0000] {process_utils.py:191} INFO - 
[2025-09-13T09:41:51.645+0000] {virtualenv.py:131} INFO - Releasing virtualenv lock
[2025-09-13T09:41:51.646+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T09:41:51.647+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 144, in execute
    output = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/base.py", line 310, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/local.py", line 853, in build_and_run_cmd
    result = self.run_command(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 128, in run_command
    self._py_bin = self._prepare_virtualenv()
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/operators/virtualenv.py", line 154, in _prepare_virtualenv
    py_bin = prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/python_virtualenv.py", line 105, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 172, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/process_utils.py", line 195, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/cosmos_venv_ecom', '--python=python3']' returned non-zero exit status 1.
[2025-09-13T09:41:51.708+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_intermediate, task_id=intermediate.categories_enriched.run, run_id=manual__2025-09-13T09:41:16.265222+00:00, execution_date=20250913T094116, start_date=20250913T094122, end_date=20250913T094151
[2025-09-13T09:41:51.737+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 218 for task intermediate.categories_enriched.run (Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/cosmos_venv_ecom', '--python=python3']' returned non-zero exit status 1.; 6357)
[2025-09-13T09:41:51.770+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-13T09:41:51.870+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T09:41:51.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
