[2025-09-12T15:19:13.635+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-12T15:19:13.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:19:12.969239+00:00 [queued]>
[2025-09-12T15:19:13.712+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:19:12.969239+00:00 [queued]>
[2025-09-12T15:19:13.723+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-12T15:19:13.748+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-09-12 15:19:12.969239+00:00
[2025-09-12T15:19:13.753+0000] {standard_task_runner.py:64} INFO - Started process 997 to run task
[2025-09-12T15:19:13.756+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_exec', 'dbt_run', 'manual__2025-09-12T15:19:12.969239+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dbt_staging.py', '--cfg-path', '/tmp/tmpue7yymlg']
[2025-09-12T15:19:13.760+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask dbt_run
[2025-09-12T15:19:13.914+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_exec.dbt_run manual__2025-09-12T15:19:12.969239+00:00 [running]> on host e95bde6b8d07
[2025-09-12T15:19:14.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_exec' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T15:19:12.969239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-12T15:19:12.969239+00:00'
[2025-09-12T15:19:14.163+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-12T15:19:14.176+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-12T15:19:14.177+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    cd /opt/***/dags/dbt/ecom_staging &&     dbt run --select models/ecom_staging/ --profiles-dir /opt/***/dags/dbt/ecom_staging/profiles.yml\n    ']
[2025-09-12T15:19:14.186+0000] {subprocess.py:86} INFO - Output:
[2025-09-12T15:19:16.319+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2025-09-12T15:19:16.320+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2025-09-12T15:19:16.320+0000] {subprocess.py:93} INFO - 
[2025-09-12T15:19:16.322+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dags/dbt/ecom_staging/profiles.yml' does not exist.
[2025-09-12T15:19:16.565+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-09-12T15:19:16.566+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-12T15:19:16.702+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-12T15:19:16.715+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_run_exec, task_id=dbt_run, run_id=manual__2025-09-12T15:19:12.969239+00:00, execution_date=20250912T151912, start_date=20250912T151913, end_date=20250912T151916
[2025-09-12T15:19:16.887+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 86 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 997)
[2025-09-12T15:19:16.903+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-12T15:19:16.974+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-12T15:19:16.986+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
